// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PranaFashion.Infrastructure.Data;

#nullable disable

namespace PranaFashion.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260329182238_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PranaFashion.Core.Models.Enquiry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Enquiries");
                });

            modelBuilder.Entity("PranaFashion.Core.Models.Order", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("text");

                    b.Property<string>("AddressPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Pincode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PranaFashion.Core.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Size")
                        .HasColumnType("text");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("PranaFashion.Core.Models.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("PranaFashion.Core.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Badge")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Colors")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Fabric")
                        .HasColumnType("text");

                    b.Property<string>("Images")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("InStock")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("OriginalPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer");

                    b.Property<string>("Sizes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StockCount")
                        .HasColumnType("integer");

                    b.Property<string>("SubCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Badge = "New Arrival",
                            Category = "women",
                            Colors = "[]",
                            CreatedAt = new DateTime(2026, 3, 29, 18, 22, 34, 609, DateTimeKind.Utc).AddTicks(4136),
                            Description = "",
                            Images = "[\"women1.jpg\"]",
                            InStock = true,
                            IsFeatured = true,
                            Name = "Kanjivaram Silk Saree",
                            OriginalPrice = 5800m,
                            Price = 4500m,
                            Rating = 4.7999999999999998,
                            ReviewCount = 34,
                            Sizes = "[]",
                            StockCount = 12,
                            SubCategory = "Sarees",
                            UpdatedAt = new DateTime(2026, 3, 29, 18, 22, 34, 609, DateTimeKind.Utc).AddTicks(4140)
                        },
                        new
                        {
                            Id = 2,
                            Badge = "Bestseller",
                            Category = "women",
                            Colors = "[]",
                            CreatedAt = new DateTime(2026, 3, 29, 18, 22, 34, 609, DateTimeKind.Utc).AddTicks(4156),
                            Description = "",
                            Images = "[\"women2.jpg\"]",
                            InStock = true,
                            IsFeatured = true,
                            Name = "Banarasi Georgette Saree",
                            Price = 3200m,
                            Rating = 4.9000000000000004,
                            ReviewCount = 51,
                            Sizes = "[]",
                            StockCount = 8,
                            SubCategory = "Wedding Collection",
                            UpdatedAt = new DateTime(2026, 3, 29, 18, 22, 34, 609, DateTimeKind.Utc).AddTicks(4157)
                        },
                        new
                        {
                            Id = 3,
                            Badge = "Sale",
                            Category = "women",
                            Colors = "[]",
                            CreatedAt = new DateTime(2026, 3, 29, 18, 22, 34, 609, DateTimeKind.Utc).AddTicks(4164),
                            Description = "",
                            Images = "[\"women3.jpg\"]",
                            InStock = true,
                            IsFeatured = true,
                            Name = "Cotton Salwar Suit Set",
                            OriginalPrice = 2200m,
                            Price = 1800m,
                            Rating = 4.5,
                            ReviewCount = 28,
                            Sizes = "[]",
                            StockCount = 20,
                            SubCategory = "Salwar Kameez",
                            UpdatedAt = new DateTime(2026, 3, 29, 18, 22, 34, 609, DateTimeKind.Utc).AddTicks(4165)
                        },
                        new
                        {
                            Id = 4,
                            Badge = "New Arrival",
                            Category = "men",
                            Colors = "[]",
                            CreatedAt = new DateTime(2026, 3, 29, 18, 22, 34, 609, DateTimeKind.Utc).AddTicks(4168),
                            Description = "",
                            Images = "[\"men1.jpg\"]",
                            InStock = true,
                            IsFeatured = true,
                            Name = "Embroidered Sherwani",
                            Price = 6500m,
                            Rating = 4.7000000000000002,
                            ReviewCount = 19,
                            Sizes = "[]",
                            StockCount = 6,
                            SubCategory = "Festive Collection",
                            UpdatedAt = new DateTime(2026, 3, 29, 18, 22, 34, 609, DateTimeKind.Utc).AddTicks(4168)
                        },
                        new
                        {
                            Id = 5,
                            Badge = "Sale",
                            Category = "men",
                            Colors = "[]",
                            CreatedAt = new DateTime(2026, 3, 29, 18, 22, 34, 609, DateTimeKind.Utc).AddTicks(4171),
                            Description = "",
                            Images = "[\"men2.jpg\"]",
                            InStock = true,
                            IsFeatured = true,
                            Name = "Cotton Kurta Set",
                            OriginalPrice = 1500m,
                            Price = 1200m,
                            Rating = 4.4000000000000004,
                            ReviewCount = 42,
                            Sizes = "[]",
                            StockCount = 25,
                            SubCategory = "Everyday Wear",
                            UpdatedAt = new DateTime(2026, 3, 29, 18, 22, 34, 609, DateTimeKind.Utc).AddTicks(4171)
                        },
                        new
                        {
                            Id = 6,
                            Badge = "Trending",
                            Category = "western",
                            Colors = "[]",
                            CreatedAt = new DateTime(2026, 3, 29, 18, 22, 34, 609, DateTimeKind.Utc).AddTicks(4175),
                            Description = "",
                            Images = "[\"western1.jpg\"]",
                            InStock = true,
                            IsFeatured = true,
                            Name = "Floral Maxi Dress",
                            Price = 2100m,
                            Rating = 4.5999999999999996,
                            ReviewCount = 23,
                            Sizes = "[]",
                            StockCount = 15,
                            SubCategory = "Western Collection",
                            UpdatedAt = new DateTime(2026, 3, 29, 18, 22, 34, 609, DateTimeKind.Utc).AddTicks(4175)
                        },
                        new
                        {
                            Id = 7,
                            Badge = "Hot Pick",
                            Category = "western",
                            Colors = "[]",
                            CreatedAt = new DateTime(2026, 3, 29, 18, 22, 34, 609, DateTimeKind.Utc).AddTicks(4179),
                            Description = "",
                            Images = "[\"western2.jpg\"]",
                            InStock = true,
                            IsFeatured = false,
                            Name = "Co-ord Set",
                            OriginalPrice = 3200m,
                            Price = 2800m,
                            Rating = 4.5,
                            ReviewCount = 16,
                            Sizes = "[]",
                            StockCount = 10,
                            SubCategory = "Fusion Wear",
                            UpdatedAt = new DateTime(2026, 3, 29, 18, 22, 34, 609, DateTimeKind.Utc).AddTicks(4179)
                        },
                        new
                        {
                            Id = 8,
                            Badge = "New Arrival",
                            Category = "kids",
                            Colors = "[]",
                            CreatedAt = new DateTime(2026, 3, 29, 18, 22, 34, 609, DateTimeKind.Utc).AddTicks(4182),
                            Description = "",
                            Images = "[\"kids1.jpg\"]",
                            InStock = true,
                            IsFeatured = true,
                            Name = "Pattu Pavadai Set",
                            Price = 1400m,
                            Rating = 4.7999999999999998,
                            ReviewCount = 31,
                            Sizes = "[]",
                            StockCount = 18,
                            SubCategory = "Girls Collection",
                            UpdatedAt = new DateTime(2026, 3, 29, 18, 22, 34, 609, DateTimeKind.Utc).AddTicks(4183)
                        });
                });

            modelBuilder.Entity("PranaFashion.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PranaFashion.Core.Models.Order", b =>
                {
                    b.HasOne("PranaFashion.Core.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PranaFashion.Core.Models.OrderItem", b =>
                {
                    b.HasOne("PranaFashion.Core.Models.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PranaFashion.Core.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PranaFashion.Core.Models.PasswordResetToken", b =>
                {
                    b.HasOne("PranaFashion.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PranaFashion.Core.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("PranaFashion.Core.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
